shortName: aegitops
fullName: AnsibleEdgeGitops
repo: https://github.com/validatedpatterns/ansible-edge-gitops
webHookName: ''
owners:
  - martjack
triggers:
  branches:
  - name: main
    versions:
    - '4.16'
    - '4.15'
    - '4.14'
  - name: 'v1.3'
    versions:
    - '4.13'
    - '4.12'

  openshift:
  - version: '4.16'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.15'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.14'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.13'
    branch: 'v1.3'
    platforms:
      - aws
    buildType: stable
  - version: '4.12'
    branch: 'v1.3'
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: gitops
    branch: main
  - name: ansible_platform
    branch: main
  - name: odf
    branch: main
  - name: cnv
    branch: main
