shortName: aegitops
fullName: AnsibleEdgeGitops
repo: https://github.com/validatedpatterns/ansible-edge-gitops
webHookName: ''
owners:
  - Martin Jackson
triggers:
  branches:
  - name: main
    versions:
    - '4.14'
  - name: 'v1.2'
    versions:
    - '4.13'
    - '4.12'
    - '4.11'

  openshift:
  - version: '4.14'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.13'
    branch: 'v1.2'
    platforms:
      - aws
    buildType: stable
  - version: '4.12'
    branch: 'v1.2'
    platforms:
      - aws
    buildType: stable
  - version: '4.11'
    branch: 'v1.2'
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: gitops
    branch: main
  - ansible_platform
    branch: main
  - name: odf
    branch: main
  - name: hco
    branch: main
