shortName: emergingdiseases
fullName: Emerging Disease Detection
repo: https://github.com/validatedpatterns/emerging-disease-detection
webHookName: ''
owners:
  - jrickard
triggers:
  branches:
  - name: main
    versions:
    - '4.15'

  openshift:
  - version: '4.15'
    branch: main
    platforms:
      - gcp
    buildType: stable

  subscriptions:
  - name: none
    branch: none
