shortName: industrialedge
fullName: IndustrialEdge
repo: https://github.com/validatedpatterns/industrial-edge
webHookName: ''
owners:
  - claudiol
triggers:
  branches:
  - name: main
    versions:
    - '4.14'
    - '4.13'
    - '4.12'
    - '4.11'

  openshift:
  - version: '4.14'
    branch: main
    platforms:
      - gcp
    buildType: stable
  - version: '4.13'
    branch: main
    platforms:
      - azure
    buildType: stable
  - version: '4.12'
    branch: 'main'
    platforms:
      - aws
    buildType: stable
  - version: '4.11'
    branch: 'main'
    platforms:
      - gcp
    buildType: stable

  subscriptions:
  - name: none
    branch: none
