shortName: devsecops
fullName: MulticlusterDevSecOps
repo: https://github.com/validatedpatterns/multicluster-devsecops
webHookName: ''
owners:
  - whenry
  - jrickard
triggers:
  branches:
  - name: main
    versions:
    - '4.16'
    - '4.15'
    - '4.14'
    - '4.13'
    - '4.12'

  openshift:
  - version: '4.16'
    branch: main
    platforms:
      - azure
    buildType: stable
  - version: '4.15'
    branch: main
    platforms:
      - gcp
    buildType: stable
  - version: '4.14'
    branch: main
    platforms:
      - azure
    buildType: stable
  - version: '4.13'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.12'
    branch: main
    platforms:
      - gcp
    buildType: stable

  subscriptions:
  - name: none
    branch: none
