shortName: openshiftai
fullName: OpenShiftAI
repo: https://github.com/validatedpatterns-sandbox/openshift-ai
webHookName: ''
owners:
  - jrickard
triggers:
  branches:
  - name: rhoai
    versions:
    - '4.17'

  openshift:
  - version: '4.17'
    branch: rhoai
    platforms:
      - baremetal
    buildType: stable
