shortName: retail
fullName: Retail
repo: https://github.com/validatedpatterns/retail
webHookName: ''
owners:
  - martjack
triggers:
  branches:
  - name: main
    versions:
    - '4.14'

  - name: v1.2
    versions:
    - '4.13'
    - '4.12'

  openshift:
  - version: '4.14'
    branch: main
    platforms:
      - aws
    buildType: stable

  - version: '4.13'
    branch: v1.2
    platforms:
      - aws
    buildType: stable

  - version: '4.12'
    branch: v1.2
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: none
    branch: none
