apiVersion: v1
baseDomain: DNS_SUBDOMAIN (example.com)
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 120
      type: Standard_D4s_v3
  replicas: 3
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    azure:
      type: Standard_D16s_v3 (equivalent to aws m5.4xlarge)
      osDisk:
        diskSizeGB: 250
  replicas: 3
metadata:
  name: CLUSTER_NAME
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.4.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    region: CLUSTER_REGION
    baseDomainResourceGroupName: RESOURCE_GROUP_WHERE_DNS_ZONE_EXISTS
    cloudName: AzurePublicCloud
pullSecret: 'JSON_PULLSECRET'
sshKey: |
  ssh-rsa SSH_PUBLIC_KEY
fips: false
publish: External
